# APEX prediction config for mutants (veltri_positive) using default pathogen set
input_dir: results/data/mutants/veltri_positive
output_dir: results/data/apex/veltri_positive/default
file_glob: "*.csv"
sequence_column: mutant
use_tqdm: true
apex_predictor_kwargs:
  path: default
  device: cuda
  batch_size: 10000
