# Batch APEX prediction config for mutants (veltri_positive) using full pathogen set
input_dir: results/data/mutants/veltri_positive
output_dir: results/data/apex/veltri_positive/all
file_glob: "*.csv"
sequence_column: mutant
use_tqdm: true
apex_predictor_kwargs:
  path: all
  device: cuda
  batch_size: 1000
