input_file: results/data/mutants/peptides_mutants.csv
output_path: results/data/physicochemical/peptides_mutants_physicochemical.csv
sequence_column: mutant
csv_separator: ","
use_tqdm: true
ph: 7.0
hydrophobicity_scale: Aboderin
