[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pep-compass-analysis"
version = "0.0.1"
description = "Analysis scripts and tools for pep-compass"
requires-python = ">=3.11, <4"

dependencies = [
    "pandas>=2.2.2",
    "loguru>=0.7.3",
    "tqdm",
    "pydantic",
    # "jax>=0.8.1",
    "pyyaml",
    "numba>=0.63.1",
    "numpy>=2.3.4",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
mutation-analysis-app = "scripts.mutation_analysis.mutation_analysis_app:main"
apex-predict = "scripts.apex.predict.predict:main"
mutang-enumerate = "scripts.mutang.enumerate_mutations_single_position.enumerate_mutations_single_position:main"
